server:
  port: 8761

spring:
  application:
    name: DiscoveryServer
eureka:
  client:
    fetch-registry: false
    register-with-eureka:  false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS

#logging:
#  file:
#    path: /logs
#  level:
#    root: DEBUG
